id = "sky"
name = "Sky"
version = "0.1.1"
schema_version = 1
authors = ["Gabriel Lima"]
description = "Sky language support for Zed"
repository = "https://github.com/clojj/sky-zed"
snippets = ["./snippets/sky.json"]

[language_servers.sky-lsp]
name = "Sky LSP"
languages = ["Sky"]

[grammars.sky]
repository = "https://github.com/anzellai/tree-sitter-sky"
rev = "dbe7d4211ee34711fa001e7d5275aa1ce365002d"
